export const TAB_OPTION_TYPE = {
	MY_GROUP_FEED: "TAB_OPTION_MY_GROUP_FEED",
	GROUP_SEARCH: "TAB_OPTION_GROUP_SEARCH",
	MY_GROUP: "TAB_OPTION_MY_GROUP",
	REQUEST_GROUP: "TAB_OPTION_REQUEST_GROUP",
};

export const TAB_OPTION_TITLE = {
	MY_GROUP_FEED: "내 그룹 피드",
	GROUP_SEARCH: "그룹 검색",
	MY_GROUP: "내 그룹",
	REQUEST_GROUP: "내가 요청중인 그룹",
};
