export const UI_TYPE = {
	PERSONAL_SCHEDULE: "PERSONAL_SCHEDULE",
	SHARE_SCHEDULE: "SHARE_SCHEDULE",
	CREATE_GROUP: "CREATE_GROUP",
	DELETE_GROUP: "DELETE_GROUP",
	DELEGATE_GROUP: "DELEGATE_GROUP",
	LEAVE_GROUP: "LEAVE_GROUP",
	WITHDRAW: "WITHDRAW",
	REQUEST_CANCEL: "REQUEST_CANCEL",
	EXIT_GROUP: "EXIT_GROUP",
};

export const SCHEDULE_MODAL_TYPE = {
	EDIT: "EDIT",
	CREATE: "CREATE",
	VIEW: "VIEW",
};
