export const UI_TYPE = {
	PERSONAL_SCHEDULE: "PERSONAL_SCHEDULE",
	SHARE_SCHEDULE: "SHARE_SCHEDULE",
	CREATE_GROUP: "CREATE_GROUP",
};

export const SCHEDULE_MODAL_TYPE = {
	EDIT: "EDIT",
	CREATE: "CREATE",
};
